// Package codegen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package codegen

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xdW3PctpL+KyzuPjhVI43ixHnQ09qyLeusfaSy7GSrfFQsDNkzg4gEGBCUJbvmv2/h",
	"RoIkwOFcNUr8kIo8BBpA99c3oAl+D2Oa5ZQA4UV4+j0s4jlkSP6JYo7vMH8Qf+eM5sA4BvUkzy9eiz/4",
	"Qw7haVhwhsksHIX3RxTl+CimCcyAHME9Z+iIo5ns9WdBSXgqOkc4CReLkfgzxTHimJJ/oww2oGjIRETQ",
	"EbTjOSIE0k3oahIWzRQVhUUNEw4zYKF4xABxSD7Jx1PKMsTD0zBBHI44ziAcrTaDZCLGVzQjXoSjak71",
	"b2JGM0bLDWQhuxtpyH9swi9FreIWTrqExM+k4IjEsP6sDQUz8QLugGmgdiVzB6zAol9nLotRyOCvEjNI",
	"wtMvYr4jDe2asbZkDQCsEWvyXTTbHG3iscGEmwoadPInxFzM2ajeFZqBQ/3UU/0vzCGTf/w3g2l4Gv7X",
	"uNbosVbncaXLi2o0xBiS/45pSbibd5xylJ75nrf4ZzU2REf2XJ0LzfMzSqZ41l1lAkXMcM7dshuFxInU",
	"xUiQScqYRwp/pExTNEkhPOWshNESDEiinoka4XanqmU7XBy6g1Ma2zUkbrOxjLcSuMOXI5u7FrPEBBQO",
	"Vg4Em2rnktQyXFwk69odC1gLp/EgSrlt7jbth+brqEaMzQx7ih4MFh6LUKNzBZtgQXrvZsGesHOtLJ57",
	"PK3WnT4mbBSdVLGEiVL0VHp5KdpIpqWUOdG3F7326JtRiQzdvwcy4/Pw9MXJyKEhKL7V+OpbrGlW91if",
	"35rAUp1SjG1qU1Pg9mS00DrAGhR1GdtcY83nolpgcbHeg2MxkRk90r+WmPB+9PiNWs2/pQFOa7p6cjVv",
	"vc5Ps8Fte7bq/HZpc6qJOpfoE3EcQ1F8QATNIAPCP7N0bdMiSUVZRSsqmYIZKvn8A03WT4BKPo8yQUBQ",
	"mwNKgF3zh3RtgopEVEgagmZKZ5hssHbZv1pvSmd0A0pUEiEwYai4Rb/74vth9AyZyATygjbFSfyyTDCQ",
	"eG0eChoRMkQM1bMUA9kgBpFUY0nE+Cfx00VRlMA2EJCkiyWVSkzit/d0Rku+KeFUUmkQvo5pDsVGVAtF",
	"QlDkmK+PdtW5435cqt+FnUazmUJT/SzFsbTcZX+AMco+QpFTUsDSZKjxz/BdmSFyxAAlItEJJKmgGYR2",
	"/EZC4y7h8D0mtwGnQULjUixZ+orgGZXPUfqTi5IcrkvqjZyF4HuAEyAcT7H0e/0uShFrhtBOdgk5vsVp",
	"KwVuMm2OirnTaYoHz1/85s5NErf/8XrgAn8Dt+/tzLrh7oZhU/4YTeVKBc1piniM2MvYl4kymsHl9YZG",
	"UZGhRcMo7ikzRUmKiZvVCS4Ewq/QQ0pR8grFt3Q6tVpOKE0BkYEja2pRrshFE01PTAPuoBFoePBh/Vy8",
	"hpSjtSeDiyiRBMToGXCUII6u8YwgXjL4WKB1RWloRYUhFrGiPcw32AL5b6D9MiTFyyTDZG1mSBIRkjTk",
	"Bt8cudXVlTAo0Y06qlCRaUyxlpwPXh5xtNhnIdfWlFUzEM0AreURUmreUfyrOlFr6r8HnX0M3NL81B7Q",
	"3pJyaxdgYK6h/1x/FuY4wMzgEDbqliT83XSRpjh++IDuP+dipsUVsCtgmEoyGSY4K7PwtN4bsPPVAcm8",
	"pB5l6D4qFf0oByb+EyMsqvEvp1McwztasmJtG6HHopJUNJe06hHUoi4IB3aH1o5d9Rhq/hE21OphrtEU",
	"WonbWqso0BTqBE79+Aln8I0S2HDy3JCpKSvZC/q05BuSV3KWowhi7UGKN0SY1GRTBhk4gSYnLT9NU1ry",
	"C3LF6IxBsT6WNKUIkyg3tKRpZCi+Heh2lu79dqfb3cGqbZSHjR3guVSqgyCPVvSZAzdWDEtcIbl0AL6d",
	"Mst2OgO7ppmz9imfOzcqB29o9hokZ5zvsitdXNUN28bBb3UtLe8jyL16X7dpad3SlrXiOEeucN5g/G+D",
	"DsuWMdnLqO6Cfcvzou1CH51cc8SdZ0lZngIHt6AT+pWIOA+S/udi5c4GVeLbfSTPdNLUR5qSdzRNevY5",
	"3Y9KksAUEx9VxbVzhgh3NhlmCzXvZ5rMwrm1GtqTaY88qrL4SgA2Rxqcb7K54oxX4pdvPrxigG5Fr8Eb",
	"zhSyqtMbwpnzFFyS9+xw+3elt3VQuvnutp6Jl3NCR8pC9hLWvJVjW9F/fSyRofyL0MFj0eFG/AsTLv+v",
	"DMJNiQn/7ddqCJ1prS6gu1bHfiHpYTZcSmcJ5hzWkcOkkM833FGRNBrbKSjFqHCfGTVrDfo4Zyb9snmW",
	"+5iHjTh3/kwhGxhJ4bw/hbZk9bKvKmNnqec+mLvNwq7tV1ylqOBnc4hv31KmQ8etMkPQj2IxQDSlzIQV",
	"1dCfbX/zaQdDN52gkUk99IbGwB7DNgmFtNF93n0LyY4et53r3G22pHoZbZWuwdfNd+oqu7qMzs6ZNEPc",
	"gHNjwSUmB/fW3Jhr1MxYqlW57mGRQ/f4X/igwSVOZlR3uNKorhrkfyvX54tMhgYljXKmvpmraOQdLjhl",
	"eI2Z2v2dkYK7YVdA+7DlMhw+W+d8XxakyO5RrLJ9cyxU/7bMcNwBw8WQ+tdK2UyPpi7Wq3AJthtj9+PS",
	"kRQ5A4RRmAOLgXAN9VpGtJykloBImU0csBRUWzV2NT3nQjI0Rx/hrxIK3o0qm0VSB1h/pmtcXqUovk2x",
	"WkKlWR3ernEgaUaIJtUQB7Mb3jwV7uOX1XIxCqc4Be+WeefEtY9us7HsTSn7CKhwHdyr34Ov84eAz3ER",
	"aGgFuAgyxG4hCVARoEDSCGoP2dj1OhktKXEeeqJDKYuYmuhCn5GvdgD6VpDoLvKCJALQUAR42llma3HB",
	"lLKAzyGIS8aA8CCmhMM9r+Gz8qmqpD+imVCCnD8oc+k+sjeDOMMv5t7aW+3tAtnEDnZKWRlS4a+9f1yo",
	"o0Upi9abCB1F70ZX7hrI2oRtv6zRskCWfRhugp6ejl/VtbBejXkMuHlrPbviaYPOQqMGnoahRq/CrJlJ",
	"D75W3k3T/YaHg1Yl8vZ31KrZuJZoEgoT/ns0ybPH0xaWbOYaxr0ztmpotWIItQLMaktW5RBLIiz5vlZc",
	"MswfroUU1ZxnmM/LyRmltxhelnyuFiUiAPmTOV871Q3rOaMc/y9IgVOcxK8AMWCGwET+661Z7r/++CSw",
	"LAcVnkQ+rSnNOc8NnQETEc2601A54ZQqoBOOYgk/yBBO5TYkJhxhAqz4H21GjlJMyvtjymY17bfqUXBG",
	"devgvWikdU9N9XRsDJHs27ac4b91naL0siRQeA1U8TE7ruoV64aWTp+GJ8cnxz9LbuRAUI7D0/CX45Pj",
	"E6kWfC5lNkY5Htsvic6Ad91/jmaYiKGrlpIoU24qCU/DK93iZd0gRwxlwIEV4ekXLYC/SmAPNY/ki3qU",
	"Xek3Zl4b0SInaN006u2HlbvaJ7Urd27siazcu9a5lbta7y12+lq20dOZIybsYq3/KtysKVWWpQo9B84L",
	"SLIbwrkwQjalnhoXPxFgfjo/uwjdiMWoWl6pKs9PToxF0HWFln8e/6mTg5r6kFc5pXdddNKi8D0ueKVs",
	"QVHKKubATEfo9K8nv3b11GhfQCgPprQkSaPPC7WCvqFU3XHdybL0UovbBvrLjWB429yqX7v+4MvN4kaQ",
	"VFYnV4duToszAx68zOVrdh5Dox4OMDJ/R/iYlwgd0DlXnPOAxgGAV0igRO6VDEBYnhdOdO0AKKMwp4UD",
	"GyqFClCed9BxJh+9lE8GQCNOKYFoymjWa4hvlFmDgr+iycM2pahjTocYdUGzTKYbC24a2MVuUWbtk3dm",
	"qHi9Haw5LZM1wJ7N0vh7OzJZqOmZSpTmRNXvTkC+lo/8gBSBWG885PenTpR2odCcqpqPV2gvlvTZgxxG",
	"fofgYvA58Mfk7j4U7VwtfYUwIM9XiQCMx9iLcPPSIVyd2Ljkqw4B9yfiRzTzDS4cjJlXAtihmf9cLfsA",
	"zPzYfhO6Pxc2LQM6Fcm5C7wmWD2rb4rYMYb/OSmU/T67x2hWEhpsObWgVrWe1UD7MaF9UbF5WcYdGZ9V",
	"T5+mLW3e5TAsbK45sj+bWt8/4QubdYvdhs5mkAOyq+Pv1a7bkJjarGDyEMgTEFd0vTdQj5wk7V3E3UTr",
	"fVh5MaDf40bt/SI8B/53kt+urYflbfbl1R4/L+hHkIofny6IfnhJf9axNS+5Lb1ozesAHGv99kp/uqLa",
	"DUhWzs39dj9SlS3hvH4tyYF04SIVy4cbdN1+Bdxaozx+jiL5EWDSs4Uv5/pk0xT7Ndph5nem17s/46tf",
	"Y/MmKFICu01P1BAHY0PH33UtwZDERGF4hu+ABJgXge4aIJIE5v5hV7KyJ2C7o5S6VmI3iUofZnxmbBUr",
	"1hjmcbOa1eV/DvzvIvzdGqBz46t2iKR6jEfPblZHknld6imC6VGdrc3xw3C2Op9Y0dk2eq2U8qysKI2h",
	"DtBVjxtls15zXbWSCdAG1vvCfgvpqWievxhQvSy2lNLyhOtxsjbfwijjb3HKZWnw6myhjF+yZM3OgFg8",
	"32Bw2f93lJawTvekVJjdBjyG1KjuMkBovCHriRMumnrtt6PeKMBJ4aAN3fh7XXu8GGT1NjB6F9YrAU/N",
	"3DUpNQq2DyMErt/ZdqO7kt/gQNiIa9VYuBrp6SB/rNxXNK/fC1+uCM0+x32Ib751/k+Fv8c3pDjDfLjD",
	"34cSta8jWKpTsn2gobBHFWsNfNAaFxXmWrZhurW1+FpdB/f0Y+y1ArKdb7s0uezQlArk10aosx3vyPhG",
	"PGj1qN6DXa4dsunWss+z6v3WH+qxE2+iGLwk67CFukHq0SVziKCnkEUT+1pAL+Yv33wY5yniU8qyoOqy",
	"KfYb10b+2EOvjXmDMQ7EXr75ELyypbBrU+4Z8BBBrfMBbl1B6YW1jttM203xrOLV6vLLH7Z8N9rhujPV",
	"oSSqWfDJEu6u1cQ75CEqit4MHOgBzFVAWzP+nWtpfziAGuId5jjwrdvs1xH0DHrIGB/kDQzEt+UONK9+",
	"+IP9KMtSh2Cwu0+P4B/zANTFvtipv9TUtBxQbHpliP7Dyk37T/8e+eDNvvrLU7Fq5DZcGaoeh3F7hLl1",
	"zF1+elU9fZoFqM3LAYeVoNYc2V9dTHX3m7cMVUtieG1Mq99kjbpUc7flARnd8ffqw9hDqlPNCupApOq+",
	"tEJ1b9h3ByD2B8B3U6XaDym/6VqjUnWPSOqpVV0PDefA/05Q2LW9Oq+94k6RZY/z6LWr6yFL1RQ+XXA9",
	"sr9u8v5Q/LUuFN2HCnxugu9A3fRY3lp9tPRCEXmzUZrWl0h8nQODAPXeJN5jreUV3vu/ceQQTLfze4V9",
	"Xxdf/Qu0jTvWT78vubd9+RfEFyP/Zcrdzv1uR0o+OFv51pOOCvYc0nNgBKVBAewOmFK9nWqc694IpVkD",
	"NiLUvfSN7QjvBSmtu3reqiGGqM96734P3Y/YZA9i63VYLe1RF/xHeftSakz4L8/DkeMWa/nVpBXab/02",
	"8ajStqWjt67JzuutqsbC7UU1B7kZoL9XreukFGaL1QoJWn336BB71HNoysogo3e1N0eFVlsR6vjV9aPs",
	"ZSvrHnR1b5mqWl1TrsPtufIDDFLJrmKO8wGm3Tnk4yUYeivGuhavac2by3uGE8hyKoxYUOHkpw5orqvL",
	"Zp4cYtbLOZr2uh27tKo25B8oDVQDqX8i7sRk1vzki/U9m2dwPDseBf8RgYGMHqEICEACSTDFKRQPBYcs",
	"KMo8p4wHnAZzRJIUAgJftVyLAE05MDWCPlP7TyhEB/coy+Xt9hbxCWfToiKIzZ34R0BmmMDgEVb+AI8z",
	"FlsMUeW3ftTqb8HUIE+Mjk/LNH3wbnFekDuU4npf8xli8RxziHnJIMhwkSEez0fBV0bJLLAQMgqAx8c/",
	"Lb0QxZrwcsNx3XZA+/Q//pdi+rYtrO9cuHYmVnrnZZPXSra/keD8pMmw/QSLKfvbUOh7A+Zzc17DQ6J2",
	"xz3hMa4+INN3g3Ggm7kuQjNPdnfjkhcQ8qY2+dTLKLXKOaBUfVLFuUr1OACS5BTLEuXmMt+p7kMspybV",
	"P52UzjAZxxPvhM4xf1dOgkshrCBGaTpB8W3wTP+c0QQCStKHbrDwXlA+mwyaaot6zqhAqsOe/3Ly3BV6",
	"JZhBLB0kZVgkBGn6YMw7JMHnj++HXLyi2vzsUAiCSj6nDH+DlXN70frnrQFQEv1YS7T7yRvKAyz8fgZE",
	"LF0YqMuL12eBWIEUVx8OpF9EHCJOb8FfomaaBf/641OAlFWRPYJncqweVPyuu36SAwzBRjWYGqEZvTuE",
	"hbV3F470PhdmWPU8CFFotRkkjK8wmVN6K52x8yheE9PtBuvkH5qu2zvPAalXt7V//r+jd+Xk6BrPCBLh",
	"0VpRfJfmuXQDR2/ugPDtp3+SfxVfmv7uCeji3c86DvGLXn6h1e8lLsXjsC9E4nDPx/dZOny5jY/CLgmJ",
	"OtMbFBG1fIKk8XHIxVl6VgGeVjF9gb/JnX9OaZAiNnOxerH4/wAAAP//340cNvqlAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
